spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Himanshu-Koshti-lab/microservice-configurations
          clone-on-start: true

server:
  port: 8085
